name: Build
on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Node 13.12.0
        uses: actions/setup-node@v1
        with:
          node-version: 13.12.0

      - name: npm install and npm run build
        run: |
          npm ci
          npm run lint
